- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Config interface 1/1/3
      aoscx_command:
        commands:
          - config
          - interface 1/1/3
          - description NOT_ASSIGNED
