- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands:
          - show run
      register: running_config

    - name: Process the running configuration
      set_fact:
        processed_config: "{{ running_config.stdout | replace('\"', '') | replace(',', '') }}"

    - name: Print the processed running configuration
      debug:
        msg: "{{ processed_config }}"
