- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands:
          - show run
      register: running_config

    - name: Print the running configuration line by line
      debug: "{{ running_config.stdout }}"
      loop: "{{ running_config.stdout }}"
