- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: True
  tasks:
  - name: Execute show run on the switch
    aoscx_command:
      commands:
        - show run
      output_file: 
      output_file_format: plain-text
