- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Configure Interface 1/1/3
      aoscx_l2_interface:
        interface: 1/1/3
        description: NOT_ASSIGNED
        
