- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: True
  tasks:
    - name: Configure Interface 1/1/5
      aoscx_l2_interface:
        interface: 1/1/5
        description: NOT_ASSIGNED
        vlan_mode: access
        vlan_access: '1000'
