- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: yes
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
