- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: True
   vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands:
          - show version
      register: version_output

    - name: Display version output
      debug:
        var: version_output
