- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: yes  
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands: ['show run']
    - name: Display hostname
      debug:
        msg: "The hostname of this system is {{ ansible_facts['hostname'] }}"
